### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by smallclover** [rongbo-j/mini-spring-v1.0#1]
请问您还现在还维护这个么(●'◡'●)

**Comment by jiangrongbo** [comment]
@smallclover 当然还维护了，写了一个新版本，增加了DTD校验bean的配置文件，一直没更新上去

**Comment by smallclover** [comment]
@rongbo-j 不介意的话想和您交流一下啦，q:932054296

**Comment by smallclover** [comment]
如果可以的话，我也想参与啦(●'◡'●)

**Comment by jiangrongbo** [comment]
@smallclover 当然可以参与啦，很欢迎哦！
